model: "pointMLPElite"
batch_size: 32
epoch: 300
num_points: 1024
learning_rate: 0.1
min_lr: 0.005
weight_decay: 0.0002
workers: 8
ptDropOut: 1.0
radii: [0.15, 2.25, 0.3375, 0.51]
max_nsample: 64
# msg, seed, receptive_field, sampling are overridden by run_training.py
